# Generated by Django 4.2.16 on 2024-10-24 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('person_type', models.CharField(max_length=30)),
                ('requester_name', models.CharField(max_length=40)),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('defult_issues', models.CharField(max_length=40)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'assigned'), ('in_progress', 'In Progress'), ('pending', 'pending'), ('resolved', 'resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile_country_code', models.CharField(max_length=20)),
                ('exe_designation', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.CharField(blank=True, max_length=40, null=True)),
                ('requirement', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stages', models.CharField(blank=True, max_length=40, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=40, null=True)),
                ('gst', models.CharField(blank=True, max_length=40, null=True)),
                ('client_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='customer.complaint_registration')),
            ],
        ),
    ]
