# Generated by Django 4.2.11 on 2024-06-10 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmapp', '0009_alter_taskactivity_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile_country_code', models.CharField(max_length=20)),
                ('exe_designation', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.CharField(blank=True, max_length=40, null=True)),
                ('requirement', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stages', models.CharField(blank=True, max_length=40, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=40, null=True)),
                ('gst', models.CharField(blank=True, max_length=40, null=True)),
                ('client_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.country')),
                ('executive_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('person_type', models.CharField(max_length=30)),
                ('requester_name', models.CharField(max_length=40)),
                ('designation', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('defult_issues', models.CharField(max_length=40)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
