# Generated by Django 4.2.11 on 2024-06-12 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0003_alter_complaint_registration_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_registration',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='complaint_registration',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
