# Generated by Django 4.2.11 on 2024-06-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_complaint_registration_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_registration',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'assigned'), ('in_progress', 'In Progress'), ('pending', 'pending'), ('resolved', 'resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
