# Generated by Django 4.2.11 on 2024-06-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_complaint_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_registration',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
