# Generated by Django 4.2.11 on 2024-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profilepics/deafault.jpg', upload_to='profilepics'),
        ),
    ]
