# Generated by Django 4.2.11 on 2024-05-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('leadstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
       
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile_country_code', models.CharField(max_length=20)),
                ('executive_name', models.CharField(blank=True, max_length=40, null=True)),
                ('exe_designation', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.CharField(blank=True, max_length=40, null=True)),
                ('requirement', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=40, null=True)),
                ('gst', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.country')),
                ('stages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadstage.leadstage')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile_country_code', models.CharField(max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.state'),
        ),
        migrations.CreateModel(
            name='bussiness_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_name', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('exe_designation', models.CharField(blank=True, max_length=40, null=True)),
                ('source', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.CharField(blank=True, max_length=40, null=True)),
                ('requirement', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=40, null=True)),
                ('gst', models.CharField(blank=True, max_length=40, null=True)),
                ('stages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leadstage.leadstage')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('MEETING', 'Meeting'), ('CALL', 'Call'), ('INTERVIEW', 'Interview'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('related_to', models.CharField(blank=True, max_length=255, null=True)),
                ('attendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
