# Generated by Django 4.2.11 on 2024-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_deletedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='incomplete', max_length=20),
        ),
    ]
