# Generated by Django 4.2.11 on 2024-06-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_taskactivity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
