# Generated by Django 4.2.11 on 2024-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_clockin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
